# Generated by Django 4.1.3 on 2022-11-13 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='action_name')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=50, verbose_name='lastname')),
                ('age', models.PositiveIntegerField(verbose_name='user_age')),
                ('sex', models.CharField(max_length=10, verbose_name='user_sex')),
                ('occupation', models.CharField(max_length=50, verbose_name='user_occupation')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='user_phone')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='user_email')),
                ('pass1', models.CharField(max_length=50, verbose_name='user_pass1')),
                ('pass2', models.CharField(max_length=50, verbose_name='user_pass2')),
            ],
        ),
        migrations.CreateModel(
            name='ActionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='action_date')),
                ('name', models.CharField(max_length=50, verbose_name='action_name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_app.user')),
            ],
        ),
    ]
